# Generated by Django 4.0.5 on 2022-06-15 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='upldated',
            new_name='updated',
        ),
    ]
